// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.StrongholdDemo.subsystems;

import org.usfirst.frc1891.StrongholdDemo.RobotMap;
import org.usfirst.frc1891.StrongholdDemo.commands.*;

import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon ballCollect = RobotMap.shooterBallCollect;
    private final CANTalon rearShoot = RobotMap.shooterRearShoot;
    private final DoubleSolenoid arm = RobotMap.shooterArm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void setBallCollect(double power) {
    	ballCollect.set(power);
    }
    
    public void setRearShoot(double power) {
    	rearShoot.set(power);
    }
    
    public void extendArm() {
    	arm.set(DoubleSolenoid.Value.kForward);
    }
    
    public void retractArm() {
    	arm.set(DoubleSolenoid.Value.kReverse);
    }
}

