// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.StrongholdDemo;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1891.StrongholdDemo.commands.*;
import org.usfirst.frc1891.StrongholdDemo.subsystems.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton raiseHorns;
    public JoystickButton collect;
    public JoystickButton shootLow;
    public JoystickButton shootHigh;
    public JoystickButton compress;
    public JoystickButton fire;
    public Joystick joystick1;
    public Joystick joystick2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(0);
        joystick2 = new Joystick(1);
        
        compress = new JoystickButton(joystick1, 6);
        compress.whileHeld(new CompressorOn());
        shootHigh = new JoystickButton(joystick1, 5);
        shootHigh.whileHeld(new HighShot());
        shootLow = new JoystickButton(joystick1, 3);
        shootLow.whileHeld(new LowShot());
        collect = new JoystickButton(joystick1, 4);
        collect.whileHeld(new Intake());
        raiseHorns = new JoystickButton(joystick1, 2);
        raiseHorns.whileHeld(new HornsUp());
        fire = new JoystickButton(joystick1, 1);
        fire.whileHeld(new Fire());


        // SmartDashboard Buttons
        SmartDashboard.putNumber("Wheel", 0);
        SmartDashboard.putData("HornsUp", new HornsUp());
        SmartDashboard.putData("HornsDown", new HornsDown());
        SmartDashboard.putData("HighShot", new HighShot());
        SmartDashboard.putData("LowShot", new LowShot());
        SmartDashboard.putData("Intake", new Intake());
        SmartDashboard.putData("CompressorOn", new CompressorOn());
        SmartDashboard.putData("CompressorOff", new CompressorOff());
        SmartDashboard.putData("JoyDrive", new JoyDrive());
        SmartDashboard.putData("Drivewheel", new DriveOneWheel((int) SmartDashboard.getNumber("Wheel")));

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

